import type { Product } from "./types";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "seed-1",
    slug: "leasebot",
    ownerName: "Ananya Iyer",
    name: "LeaseBot",
    shortDescription: "AI agent that qualifies rental leads on WhatsApp for Indian brokers.",
    fullDescription:
      "Connects to 99acres / Housing screenshots, replies in Hinglish, books site visits, and logs every lead. Built for brokers in Noida, Thane, and Hyderabad. Next.js + a simple WhatsApp Cloud API worker. One operator can run 4 desks.",
    productType: "AI Agent",
    niche: "Real Estate",
    tags: ["AI", "Real Estate", "WhatsApp"],
    askingInr: 1_20_000,
    thumbnailUrl: "",
    images: [],
    demoUrl: "https://vibemrr.vercel.app",
    websiteUrl: "",
    status: "available",
    isDemo: true,
    createdAt: "2026-07-12T00:00:00.000Z",
    views: 412,
    interested: 28,
    bidCount: 6,
    rating: 4.6,
    reviewCount: 3,
  },
  {
    id: "seed-2",
    slug: "gst-lite",
    ownerName: "Mehul Patel",
    name: "GST Lite",
    shortDescription: "GSTR-1 / 3B helper for CA firms that still live in Excel.",
    fullDescription:
      "Uploads Tally / Zoho export, flags ITC mismatches, and produces a filing checklist. 90-day trial with 11 CA firms. Code is Next.js + Python. Asking includes domain and sample data, not the production GSTIN list.",
    productType: "Web App / SaaS",
    niche: "Finance",
    tags: ["Finance", "Productivity"],
    askingInr: 2_40_000,
    thumbnailUrl: "",
    images: [],
    demoUrl: "",
    websiteUrl: "",
    status: "available",
    isDemo: true,
    createdAt: "2026-06-02T00:00:00.000Z",
    views: 890,
    interested: 41,
    bidCount: 11,
    rating: 4.8,
    reviewCount: 7,
  },
  {
    id: "seed-3",
    slug: "clinic-queue",
    ownerName: "Dr. Aisha Rahman",
    name: "Clinic Queue",
    shortDescription: "Tablet queue + e-Rx for neighbourhood clinics.",
    fullDescription:
      "Works on a ₹15k Android tablet. UPI checkout at the desk, WhatsApp reminders, and a paperless Rx pad. 73 clinics on the original stack; this listing is the white-label Next.js + Supabase version.",
    productType: "Mobile App",
    niche: "Healthcare",
    tags: ["Healthcare", "Local Business"],
    askingInr: 90_000,
    thumbnailUrl: "",
    images: [],
    demoUrl: "",
    status: "available",
    isDemo: true,
    createdAt: "2026-08-01T00:00:00.000Z",
    views: 210,
    interested: 19,
    bidCount: 4,
    reviewCount: 0,
  },
  {
    id: "seed-4",
    slug: "campus-resume",
    ownerName: "Priya Nair",
    name: "Campus Resume",
    shortDescription: "ATS templates that survive TCS / Infosys campus filters.",
    fullDescription:
      "One-click cleaner for photos and two-column layouts. Seasonal spikes every Aug–Nov. Next.js + Razorpay. Includes the template pack and Instagram creatives.",
    productType: "Website",
    niche: "Education",
    tags: ["Education", "AI"],
    askingInr: 45_000,
    thumbnailUrl: "",
    images: [],
    demoUrl: "",
    status: "available",
    isDemo: true,
    createdAt: "2026-05-20T00:00:00.000Z",
    views: 1560,
    interested: 88,
    bidCount: 9,
    rating: 4.4,
    reviewCount: 12,
  },
  {
    id: "seed-5",
    slug: "inbox-desi",
    ownerName: "Dev Sharma",
    name: "Inbox Desi",
    shortDescription: "Shared WhatsApp inbox for D2C brands that hate $99/mo tools.",
    fullDescription:
      "Assign chats, canned Hinglish replies, Razorpay payment links. Priced in rupees. Built with Cursor over two weekends. Source + domain included.",
    productType: "Web App / SaaS",
    niche: "Marketing",
    tags: ["Marketing", "Sales", "Social Media"],
    askingInr: 1_80_000,
    thumbnailUrl: "",
    images: [],
    demoUrl: "",
    status: "available",
    isDemo: true,
    createdAt: "2026-04-11T00:00:00.000Z",
    views: 640,
    interested: 33,
    bidCount: 8,
    rating: 4.2,
    reviewCount: 4,
  },
  {
    id: "seed-6",
    slug: "prop-scout",
    ownerName: "Karthik Rao",
    name: "Prop Scout",
    shortDescription: "AI agent that watches 99acres for a given micro-market.",
    fullDescription:
      "Daily digest of new listings matching budget + bhk + commute. Telegram + email. Real-estate niche, AI agent type — the exact search the spec describes.",
    productType: "AI Agent",
    niche: "Real Estate",
    tags: ["AI", "Real Estate"],
    askingInr: 75_000,
    thumbnailUrl: "",
    images: [],
    demoUrl: "",
    status: "available",
    isDemo: true,
    createdAt: "2026-08-08T00:00:00.000Z",
    views: 305,
    interested: 22,
    bidCount: 5,
    reviewCount: 1,
    rating: 5,
  },
  {
    id: "seed-7",
    slug: "kirana-pos",
    ownerName: "Amit Joshi",
    name: "Kirana POS",
    shortDescription: "Offline-first barcode POS in Hindi + English.",
    fullDescription:
      "Flutter app + Firebase. Credit khata, expiry alerts, daily P&L. Aimed at shops that will never pay for a US POS. Asking includes Play listing draft.",
    productType: "Mobile App",
    niche: "Local Business",
    tags: ["Local Business", "E-commerce"],
    askingInr: 55_000,
    thumbnailUrl: "",
    images: [],
    status: "available",
    isDemo: true,
    createdAt: "2026-03-18T00:00:00.000Z",
    views: 270,
    interested: 14,
    bidCount: 2,
    reviewCount: 0,
  },
  {
    id: "seed-8",
    slug: "ugc-factory",
    ownerName: "Neha Gupta",
    name: "UGC Factory",
    shortDescription: "Template pack + prompt library for Indian D2C UGC ads.",
    fullDescription:
      "40 shot lists, 12 voiceover scripts in Hinglish, CapCut templates. Not a SaaS — a template product with a Gumroad-style instant download after purchase.",
    productType: "Template",
    niche: "Creator Tools",
    tags: ["Creator Tools", "Marketing"],
    askingInr: 12_000,
    thumbnailUrl: "",
    images: [],
    status: "available",
    isDemo: true,
    createdAt: "2026-08-14T00:00:00.000Z",
    views: 980,
    interested: 120,
    bidCount: 3,
    rating: 4.9,
    reviewCount: 18,
  },
];
