import type { Startup } from "./types";

export const STARTUPS: Startup[] = [
  {
    slug: "whatsly",
    name: "Whatsly",
    tagline: "WhatsApp CRM that actually closes Indian SMBs",
    description:
      "Shared WhatsApp inbox, AI replies in Hinglish, catalogues, and Razorpay payment links. Built for agencies, clinics, and D2C brands that live in WhatsApp.",
    category: "SaaS",
    website: "https://whatsly.in",
    logoLetter: "W",
    logoColor: "#25D366",
    forSale: false,
    revenue30dInr: 3_62_000,
    mrrInr: 3_41_000,
    allTimeInr: 48_20_000,
    momGrowth: 11,
    activeSubs: 428,
    customers: 461,
    users: 1900,
    profitMargin: 64,
    provider: "razorpay",
    lastSynced: "2026-08-19T06:40:00+05:30",
    founded: "2023-11-01",
    city: "Bengaluru",
    companyType: "pvt-ltd",
    gstin: "29AABCW1234A1Z5",
    founder: { name: "Ananya Iyer", handle: "ananyaBuilds", followers: 18400, whatsapp: "919845551001" },
    vibeCoded: false,
    vibeTools: [],
    funding: "Bootstrapped",
    teamSize: 4,
    audience: "B2B",
    pricing: "₹1,499 / ₹3,999 / ₹9,999 per month",
    valueProp: "Turn missed WhatsApp chats into invoices without hiring a 10-person support team.",
    problem: "Indian SMBs lose deals in personal WhatsApp. Shared inboxes from the US are priced in dollars and ignore UPI.",
    tech: { frontend: ["Next.js", "React", "Tailwind"], backend: ["Node.js", "PostgreSQL", "Redis", "Razorpay"] },
    channels: ["WhatsApp", "LinkedIn", "Cold email", "YouTube"],
    listingTier: "free",
    githubContrib: 612,
    domainRating: 34,
  },
  {
    slug: "shikshapay",
    name: "ShikshaPay",
    tagline: "Fee collection + EMI for coaching institutes",
    description:
      "Collects school and coaching fees over UPI Autopay, cards, and cash-at-counter. Parents get receipts on WhatsApp. Institutes get a ledger their CA actually understands.",
    category: "Education",
    website: "https://shikshapay.in",
    logoLetter: "S",
    logoColor: "#F59E0B",
    forSale: false,
    revenue30dInr: 28_40_000,
    mrrInr: 27_10_000,
    allTimeInr: 3_12_00_000,
    momGrowth: 6,
    activeSubs: 214,
    customers: 226,
    users: 180000,
    profitMargin: 41,
    provider: "cashfree",
    lastSynced: "2026-08-19T05:10:00+05:30",
    founded: "2021-06-01",
    city: "Jaipur",
    companyType: "pvt-ltd",
    founder: { name: "Rohit Sharma", handle: "rohitshiksha", followers: 6200 },
    vibeCoded: false,
    vibeTools: [],
    funding: "Seed",
    teamSize: 18,
    audience: "B2B2C",
    pricing: "1.4% + ₹2 per collection · SaaS ₹4,999/mo",
    valueProp: "Institutes stop chasing fees on Excel. Parents pay in 2 taps.",
    problem: "Coaching centres still collect fees in cash and Google Sheets. Chargebacks and leftover EMI chaos follow.",
    tech: { frontend: ["Flutter", "Next.js"], backend: ["Java", "PostgreSQL", "Cashfree"] },
    channels: ["Field sales", "WhatsApp", "Education expos"],
    listingTier: "free",
    domainRating: 41,
  },
  {
    slug: "filgst",
    name: "FilGST",
    tagline: "GST filing that CAs don't hate",
    description:
      "Pulls GSTR-1 / 3B from Tally, Zoho Books, and Razorpay exports. Flags ITC mismatches before the portal does. Used by 90+ CA firms.",
    category: "Fintech",
    website: "https://filgst.com",
    logoLetter: "F",
    logoColor: "#6366F1",
    forSale: true,
    askingInr: 42_00_000,
    revenue30dInr: 1_18_000,
    mrrInr: 1_12_000,
    allTimeInr: 16_40_000,
    momGrowth: 8,
    activeSubs: 96,
    customers: 104,
    users: 380,
    profitMargin: 71,
    provider: "razorpay",
    lastSynced: "2026-08-19T01:22:00+05:30",
    founded: "2024-04-01",
    city: "Ahmedabad",
    companyType: "llp",
    founder: { name: "Mehul Patel", handle: "mehulca", followers: 3100, whatsapp: "919898221145" },
    vibeCoded: true,
    vibeTools: ["cursor", "claude"],
    funding: "Bootstrapped",
    teamSize: 2,
    audience: "B2B",
    pricing: "₹799/mo per GSTIN · Firms ₹4,999/mo",
    valueProp: "File on time, catch ITC leaks, and stop living inside the GST portal.",
    problem: "SMEs and CAs still reconcile GSTR in Excel the night before the deadline.",
    sellerMessage:
      "Selling because I'm joining a Big 4 tax tech team. Product is profitable, support is WhatsApp-only, ~6 hrs/week. Happy to do a 30-day handover.",
    additionalInfo: "AWS bill ~₹9k/mo. No employees. All customers on annual plans starting April.",
    tech: { frontend: ["Next.js", "TypeScript"], backend: ["Supabase", "Python", "Razorpay"] },
    channels: ["CA WhatsApp groups", "LinkedIn", "YouTube"],
    listingTier: "growth",
    githubContrib: 214,
    domainRating: 18,
  },
  {
    slug: "ca-workbench",
    name: "CA Workbench",
    tagline: "Practice OS for chartered accountants",
    description:
      "Client onboarding, task boards, e-sign, DSC reminders, and billing in one place. Replaces 4 Google Sheets and a dusty desktop exe.",
    category: "SaaS",
    website: "https://caworkbench.in",
    logoLetter: "C",
    logoColor: "#0EA5E9",
    forSale: false,
    revenue30dInr: 2_94_000,
    mrrInr: 2_81_000,
    allTimeInr: 39_50_000,
    momGrowth: 4,
    activeSubs: 187,
    customers: 192,
    profitMargin: 58,
    provider: "razorpay",
    lastSynced: "2026-08-18T22:05:00+05:30",
    founded: "2023-01-01",
    city: "Pune",
    companyType: "pvt-ltd",
    founder: { name: "Sneha Kulkarni", handle: "snehaca", followers: 8900 },
    vibeCoded: false,
    vibeTools: [],
    funding: "Bootstrapped",
    teamSize: 5,
    audience: "B2B",
    pricing: "₹2,499 – ₹12,999 / month",
    valueProp: "Run a 40-client CA firm without a dedicated ops person.",
    problem: "Indian CA firms outgrow Excel but can't swallow Practice Evolve pricing.",
    tech: { frontend: ["React", "Vite"], backend: ["NestJS", "PostgreSQL", "Razorpay"] },
    channels: ["ICAI chapters", "LinkedIn", "Webinars"],
    listingTier: "free",
    domainRating: 27,
  },
  {
    slug: "shipdukaan",
    name: "ShipDukaan",
    tagline: "One dashboard for Delhivery, Bluedart, and Shiprocket rates",
    description:
      "Compares last-mile rates across couriers, auto-picks the cheapest SLA, and pushes tracking to the buyer's WhatsApp. Built for D2C brands doing 200–5,000 orders/month.",
    category: "Logistics",
    website: "https://shipdukaan.com",
    logoLetter: "D",
    logoColor: "#EF4444",
    forSale: false,
    revenue30dInr: 4_88_000,
    mrrInr: 4_62_000,
    allTimeInr: 61_00_000,
    momGrowth: 9,
    activeSubs: 156,
    customers: 164,
    profitMargin: 36,
    provider: "cashfree",
    lastSynced: "2026-08-19T03:44:00+05:30",
    founded: "2022-09-01",
    city: "Gurugram",
    companyType: "pvt-ltd",
    founder: { name: "Kabir Singh", handle: "kabirships", followers: 11200 },
    vibeCoded: false,
    vibeTools: [],
    funding: "Angel",
    teamSize: 7,
    audience: "B2B",
    pricing: "₹2,999/mo + per-shipment markup",
    valueProp: "Stop overpaying Shiprocket because you never compared the actual rate card.",
    problem: "D2C brands lock into one aggregator and bleed 8–15% extra on every north-east and COD shipment.",
    tech: { frontend: ["Next.js"], backend: ["Go", "PostgreSQL", "Redis"] },
    channels: ["Shopify app store", "Twitter", "D2C WhatsApp groups"],
    listingTier: "free",
    domainRating: 29,
  },
  {
    slug: "clinicstack",
    name: "ClinicStack",
    tagline: "Appointment + Rx OS for neighbourhood clinics",
    description:
      "Queue management, e-prescriptions, WhatsApp reminders, and UPI checkout at the front desk. Works on a ₹15k Android tablet.",
    category: "Health",
    website: "https://clinicstack.in",
    logoLetter: "K",
    logoColor: "#14B8A6",
    forSale: true,
    askingInr: 9_00_000,
    revenue30dInr: 51_400,
    mrrInr: 48_200,
    allTimeInr: 6_10_000,
    momGrowth: 14,
    activeSubs: 73,
    customers: 73,
    users: 210,
    profitMargin: 68,
    provider: "phonepe",
    lastSynced: "2026-08-19T07:01:00+05:30",
    founded: "2025-02-01",
    city: "Hyderabad",
    companyType: "opc",
    founder: { name: "Dr. Aisha Rahman", handle: "aishabuilds", followers: 2400, whatsapp: "919490012388" },
    vibeCoded: true,
    vibeTools: ["cursor", "grok"],
    funding: "Bootstrapped",
    teamSize: 1,
    audience: "B2B",
    pricing: "₹999 / ₹1,999 per clinic / month",
    valueProp: "A clinic can go paperless in an afternoon without Practo-level pricing.",
    problem: "Small clinics still use a register + a receptionist's memory. No-shows kill the day.",
    sellerMessage:
      "I'm going back to clinical practice full-time. The app is stable, 73 paying clinics, support is a WhatsApp broadcast. Code is Next.js + Supabase — any vibe coder can own it.",
    tech: { frontend: ["Next.js", "React Native"], backend: ["Supabase", "PhonePe"] },
    channels: ["Doctor Facebook groups", "WhatsApp", "Clinic visits"],
    listingTier: "starter",
    githubContrib: 340,
    domainRating: 8,
  },
  {
    slug: "billupi",
    name: "BillUPI",
    tagline: "GST invoices + UPI for freelancers",
    description:
      "Create a GST invoice, share a UPI QR / payment link, and auto-reconcile. TDS section 194J reminder baked in. Favourite of designers and indie hackers.",
    category: "Fintech",
    website: "https://billupi.in",
    logoLetter: "B",
    logoColor: "#8B5CF6",
    forSale: true,
    askingInr: 18_00_000,
    revenue30dInr: 86_000,
    mrrInr: 82_400,
    allTimeInr: 9_40_000,
    momGrowth: 7,
    activeSubs: 310,
    customers: 338,
    users: 4100,
    profitMargin: 79,
    provider: "razorpay",
    lastSynced: "2026-08-19T04:18:00+05:30",
    founded: "2024-08-01",
    city: "Bengaluru",
    companyType: "proprietorship",
    founder: { name: "Dev Sharma", handle: "devships", followers: 15600, whatsapp: "919900112233" },
    vibeCoded: true,
    vibeTools: ["cursor", "claude", "grok"],
    funding: "Bootstrapped",
    teamSize: 1,
    audience: "B2C",
    pricing: "Free · Pro ₹299/mo · GSTIN pack ₹599/mo",
    valueProp: "Send a legal invoice and get paid on UPI without Zoho Books overhead.",
    problem: "Indian freelancers either skip GST invoices or drown in Zoho. Clients pay late because there is no UPI link.",
    sellerMessage:
      "Shipping a new product. BillUPI is profitable and mostly passive. 310 subs, 79% margin, Stripe+Razorpay. Want a founder who will push annual plans.",
    tech: { frontend: ["Next.js", "Tailwind"], backend: ["Supabase", "Razorpay"] },
    channels: ["Twitter", "Peerlist", "Product Hunt India"],
    listingTier: "growth",
    githubContrib: 188,
    domainRating: 16,
  },
  {
    slug: "resumedesi",
    name: "ResumeDesi",
    tagline: "ATS resumes that survive campus placements",
    description:
      "Templates tuned for TCS / Infosys / startup ATS, IIT/NIT project bullets, and a one-click 'remove photo + caste signals' cleaner. Viral on LinkedIn every placement season.",
    category: "Education",
    website: "https://resumedesi.com",
    logoLetter: "R",
    logoColor: "#F97316",
    forSale: true,
    askingInr: 6_00_000,
    revenue30dInr: 34_800,
    mrrInr: 33_100,
    allTimeInr: 4_20_000,
    momGrowth: 22,
    activeSubs: 890,
    customers: 2100,
    users: 48000,
    profitMargin: 88,
    provider: "razorpay",
    lastSynced: "2026-08-18T20:40:00+05:30",
    founded: "2025-07-01",
    city: "Remote · India",
    companyType: "unregistered",
    founder: { name: "Priya Nair", handle: "priyacodes", followers: 7200, whatsapp: "919995551234" },
    vibeCoded: true,
    vibeTools: ["cursor", "lovable"],
    funding: "Bootstrapped",
    teamSize: 1,
    audience: "B2C",
    pricing: "₹199 one-time · ₹99/mo Pro",
    valueProp: "A campus resume that doesn't get auto-rejected for a photo or a two-column layout.",
    problem: "Students copy US resume templates. Indian ATS and college formats hate them.",
    sellerMessage: "Vibe-coded in a weekend before my own placements. Seasonal but spikes every Aug–Nov. Easy to run.",
    tech: { frontend: ["Next.js"], backend: ["Vercel", "Razorpay"] },
    channels: ["LinkedIn", "Instagram", "College WhatsApp"],
    listingTier: "starter",
    githubContrib: 46,
    domainRating: 11,
  },
  {
    slug: "kiranos",
    name: "KiranaOS",
    tagline: "Inventory + UPI ledger for kirana stores",
    description:
      "Barcode stock, credit khata, and daily P&L in Hindi + English. Syncs offline. Shopkeepers use it on a second-hand Redmi.",
    category: "SaaS",
    website: "https://kiranaos.in",
    logoLetter: "K",
    logoColor: "#84CC16",
    forSale: true,
    askingInr: 4_50_000,
    revenue30dInr: 28_600,
    mrrInr: 27_100,
    allTimeInr: 3_10_000,
    momGrowth: 5,
    activeSubs: 214,
    customers: 214,
    profitMargin: 54,
    provider: "payu",
    lastSynced: "2026-08-19T02:11:00+05:30",
    founded: "2024-12-01",
    city: "Indore",
    companyType: "proprietorship",
    founder: { name: "Amit Joshi", handle: "amitkirana", followers: 980, whatsapp: "919826001199" },
    vibeCoded: true,
    vibeTools: ["windsurf", "copilot"],
    funding: "Bootstrapped",
    teamSize: 1,
    audience: "B2B",
    pricing: "₹399 / month per store",
    valueProp: "A kirana owner knows what expired, who owes him, and today's cash — without a CA on speed dial.",
    problem: "Bharat kiranas still run on a notebook. Digital khata apps are ads with a calculator.",
    sellerMessage: "Need capital to hire 2 city salespeople. Open to a full sale or an operator who wants the distribution side.",
    tech: { frontend: ["Flutter"], backend: ["Firebase", "PayU"] },
    channels: ["Field sales", "Kirana associations", "YouTube"],
    listingTier: "starter",
    domainRating: 6,
  },
  {
    slug: "nammamenu",
    name: "NammaMenu",
    tagline: "QR menu + UPI for Udupi and cloud kitchens",
    description:
      "Photo menu, veg/non-veg filters, and table-wise UPI. Owners get a Telegram ping on every order. No Play Store tax.",
    category: "SaaS",
    website: "https://nammamenu.in",
    logoLetter: "N",
    logoColor: "#E11D48",
    forSale: true,
    askingInr: 2_80_000,
    revenue30dInr: 19_400,
    mrrInr: 18_600,
    allTimeInr: 1_72_000,
    momGrowth: 18,
    activeSubs: 61,
    customers: 61,
    profitMargin: 72,
    provider: "razorpay",
    lastSynced: "2026-08-19T08:05:00+05:30",
    founded: "2026-01-01",
    city: "Bengaluru",
    companyType: "unregistered",
    founder: { name: "Karthik Rao", handle: "karthikvibe", followers: 2100, whatsapp: "919611228877" },
    vibeCoded: true,
    vibeTools: ["cursor", "grok"],
    funding: "Bootstrapped",
    teamSize: 1,
    audience: "B2B",
    pricing: "₹499 / month",
    valueProp: "A QR on the table replaces a 40-page laminated menu and a missed order.",
    problem: "Small restaurants pay Zomato 20% or print menus that go stale every festival.",
    sellerMessage: "Shipped this on a long weekend. 61 kitchens, almost no support. Want to focus on a new AI product.",
    tech: { frontend: ["Next.js"], backend: ["Supabase", "Razorpay"] },
    channels: ["Instagram", "Walking into restaurants", "Twitter"],
    listingTier: "starter",
    githubContrib: 71,
    domainRating: 4,
  },
  {
    slug: "paysplit",
    name: "PaySplit",
    tagline: "Split rent, Wi-Fi, and tiffin on UPI",
    description:
      "Create a house, add roommates, settle in one UPI collect. Built for PG and flatmates in Koramangala / Hinjewadi / Gachibowli.",
    category: "Fintech",
    website: "https://paysplit.app",
    logoLetter: "P",
    logoColor: "#06B6D4",
    forSale: true,
    askingInr: 80_000,
    revenue30dInr: 8_400,
    mrrInr: 7_900,
    allTimeInr: 54_000,
    momGrowth: 31,
    activeSubs: 142,
    customers: 390,
    users: 1800,
    profitMargin: 91,
    provider: "razorpay",
    lastSynced: "2026-08-19T09:12:00+05:30",
    founded: "2026-03-01",
    city: "Pune",
    companyType: "unregistered",
    founder: { name: "Neha Gupta", handle: "nehavibes", followers: 640, whatsapp: "919823334455" },
    vibeCoded: true,
    vibeTools: ["cursor", "replit"],
    funding: "Bootstrapped",
    teamSize: 1,
    audience: "B2C",
    pricing: "Free · Plus ₹49/mo per house",
    valueProp: "Stop asking 'did you pay the cook' in the flat WhatsApp group.",
    problem: "Splitwise is USD-brained. Indian flats need UPI collect, not IOUs.",
    sellerMessage: "Tiny but growing 31% MoM. Perfect first acquisition for a vibe coder. Asking less than 1x.",
    tech: { frontend: ["Next.js"], backend: ["Supabase", "Razorpay"] },
    channels: ["College groups", "Twitter", "Product Hunt"],
    listingTier: "starter",
    githubContrib: 39,
    domainRating: 3,
  },
  {
    slug: "brokerbook",
    name: "BrokerBook",
    tagline: "CRM for local real-estate brokers",
    description:
      "Lead capture from 99acres / Housing screenshots, site-visit calendar, and WhatsApp follow-ups. Brokers in Noida and Thane actually use it daily.",
    category: "SaaS",
    website: "https://brokerbook.in",
    logoLetter: "B",
    logoColor: "#A855F7",
    forSale: true,
    askingInr: 8_00_000,
    revenue30dInr: 41_200,
    mrrInr: 39_400,
    allTimeInr: 5_10_000,
    momGrowth: 3,
    activeSubs: 88,
    customers: 91,
    profitMargin: 61,
    provider: "cashfree",
    lastSynced: "2026-08-18T18:30:00+05:30",
    founded: "2024-06-01",
    city: "Noida",
    companyType: "opc",
    founder: { name: "Harsh Vardhan", handle: "harshbroker", followers: 1300, whatsapp: "919810009988" },
    vibeCoded: false,
    vibeTools: ["copilot"],
    funding: "Bootstrapped",
    teamSize: 2,
    audience: "B2B",
    pricing: "₹1,499 / month per desk",
    valueProp: "A broker's entire pipeline lives in one place instead of 14 WhatsApp chats.",
    problem: "Indian brokers lose listings because follow-ups sit in their personal phone.",
    sellerMessage: "Co-founder leaving for an MBA. Clean books, 88 desks, ready for a sales-led buyer.",
    tech: { frontend: ["React"], backend: ["Laravel", "MySQL", "Cashfree"] },
    channels: ["Broker associations", "Facebook", "Field"],
    listingTier: "starter",
    domainRating: 9,
  },
  {
    slug: "batchly",
    name: "Batchly",
    tagline: "LMS + live class for offline coaching centres",
    description:
      "Attendance, recorded lectures, test series, and parent WhatsApp reports. Used by JEE/NEET centres that are not ready for a full Unacademy clone.",
    category: "Education",
    website: "https://batchly.in",
    logoLetter: "B",
    logoColor: "#2563EB",
    forSale: false,
    revenue30dInr: 1_92_000,
    mrrInr: 1_84_000,
    allTimeInr: 22_00_000,
    momGrowth: 2,
    activeSubs: 54,
    customers: 54,
    users: 22000,
    profitMargin: 47,
    provider: "razorpay",
    lastSynced: "2026-08-19T00:50:00+05:30",
    founded: "2023-05-01",
    city: "Kota",
    companyType: "pvt-ltd",
    founder: { name: "Vikram Singh", handle: "vikrambatch", followers: 4400 },
    vibeCoded: false,
    vibeTools: [],
    funding: "Bootstrapped",
    teamSize: 6,
    audience: "B2B",
    pricing: "₹7,999 – ₹24,999 / month",
    valueProp: "Give an offline centre an online twin without building an app.",
    problem: "Kota and Hyderabad centres lost students to recorded-content apps and had no LMS of their own.",
    tech: { frontend: ["Next.js", "Flutter"], backend: ["Node.js", "MongoDB", "Razorpay"] },
    channels: ["Field sales", "Education expos"],
    listingTier: "free",
    domainRating: 19,
  },
  {
    slug: "stealth-fintech",
    name: "Stealth Company",
    anonymous: true,
    tagline: "B2B payouts infrastructure",
    description:
      "Confidential payouts and vendor payments product for Indian enterprises. Brand hidden. Metrics verified on Cashfree.",
    category: "Fintech",
    logoLetter: "S",
    logoColor: "#52525B",
    forSale: false,
    revenue30dInr: 13_10_000,
    mrrInr: 12_40_000,
    allTimeInr: 1_48_00_000,
    momGrowth: 5,
    activeSubs: 38,
    customers: 41,
    profitMargin: 33,
    provider: "cashfree",
    lastSynced: "2026-08-18T16:00:00+05:30",
    founded: "2022-02-01",
    city: "Mumbai",
    companyType: "pvt-ltd",
    founder: { name: "Hidden Founder", handle: "stealthin", followers: 120 },
    vibeCoded: false,
    vibeTools: [],
    funding: "Seed",
    teamSize: 11,
    audience: "B2B",
    pricing: "Custom · starting ₹49,000 / month",
    valueProp: "Enterprises move vendor payouts off NEFT-and-Excel.",
    problem: "Finance teams still download a bank CSV and pray.",
    tech: { frontend: ["Next.js"], backend: ["Go", "PostgreSQL"] },
    channels: ["Outbound", "LinkedIn"],
    listingTier: "free",
    domainRating: 0,
  },
  {
    slug: "codeseva",
    name: "CodeSeva",
    tagline: "AI support agent trained on your Indian SaaS docs",
    description:
      "Answers users in English + Hinglish, files Linear tickets, and knows GST/UPI edge cases. Built for support teams of 1.",
    category: "Artificial Intelligence",
    website: "https://codeseva.ai",
    logoLetter: "C",
    logoColor: "#F43F5E",
    forSale: true,
    askingInr: 48_00_000,
    revenue30dInr: 1_58_000,
    mrrInr: 1_51_000,
    allTimeInr: 11_20_000,
    momGrowth: 19,
    activeSubs: 67,
    customers: 71,
    profitMargin: 62,
    provider: "stripe",
    lastSynced: "2026-08-19T06:02:00+05:30",
    founded: "2025-05-01",
    city: "Bengaluru",
    companyType: "pvt-ltd",
    founder: { name: "Arjun Mehta", handle: "arjunseva", followers: 9800, whatsapp: "919900445566" },
    vibeCoded: true,
    vibeTools: ["cursor", "claude", "grok"],
    funding: "Bootstrapped",
    teamSize: 2,
    audience: "B2B",
    pricing: "₹4,999 – ₹19,999 / month",
    valueProp: "A support agent that understands 'payment failed but UPI deducted'.",
    problem: "US helpdesks hallucinate on GST invoices and Razorpay webhooks.",
    sellerMessage:
      "Raising for a new model lab. CodeSeva is clean, 67 customers, 19% MoM. Prefer an Indian acquirer who can sell into Zoho/Freshworks shops.",
    tech: { frontend: ["Next.js"], backend: ["Python", "Postgres", "Stripe"] },
    channels: ["Twitter", "Hacker News", "Peerlist"],
    listingTier: "scale",
    githubContrib: 402,
    domainRating: 22,
  },
  {
    slug: "tdsmate",
    name: "TDSMate",
    tagline: "TDS, Form 16, and 26AS without the portal rage",
    description:
      "Calculates TDS, generates Form 16, and matches 26AS. Used by boutique CA firms and startup finance teams.",
    category: "Fintech",
    website: "https://tdsmate.in",
    logoLetter: "T",
    logoColor: "#10B981",
    forSale: false,
    revenue30dInr: 64_800,
    mrrInr: 61_200,
    allTimeInr: 7_80_000,
    momGrowth: 4,
    activeSubs: 128,
    customers: 135,
    profitMargin: 74,
    provider: "razorpay",
    lastSynced: "2026-08-19T01:55:00+05:30",
    founded: "2024-02-01",
    city: "Chennai",
    companyType: "llp",
    founder: { name: "Lakshmi Narayan", handle: "lakshmitds", followers: 2100 },
    vibeCoded: false,
    vibeTools: [],
    funding: "Bootstrapped",
    teamSize: 2,
    audience: "B2B",
    pricing: "₹699 / month",
    valueProp: "Finish TDS week without logging into traces 40 times.",
    problem: "The government portal is the product. Everything around it is pain.",
    tech: { frontend: ["Next.js"], backend: ["Django", "PostgreSQL"] },
    channels: ["CA WhatsApp", "LinkedIn"],
    listingTier: "free",
    domainRating: 12,
  },
  {
    slug: "anonymous-voice",
    name: "Anonymous Startup",
    anonymous: true,
    tagline: "AI voice agents for Indian SMBs",
    description:
      "Hindi + English voice agents that book appointments and qualify leads. Brand hidden while the founder evaluates inbound.",
    category: "Artificial Intelligence",
    logoLetter: "A",
    logoColor: "#71717A",
    forSale: true,
    askingInr: 1_20_00_000,
    revenue30dInr: 6_40_000,
    mrrInr: 6_18_000,
    allTimeInr: 42_00_000,
    momGrowth: 16,
    activeSubs: 49,
    customers: 52,
    profitMargin: 44,
    provider: "stripe",
    lastSynced: "2026-08-19T07:40:00+05:30",
    founded: "2025-01-01",
    city: "Bengaluru",
    companyType: "pvt-ltd",
    founder: { name: "Anonymous", handle: "anonvoice", followers: 0, whatsapp: "919999000011" },
    vibeCoded: false,
    vibeTools: ["claude"],
    funding: "Angel",
    teamSize: 4,
    audience: "B2B",
    pricing: "₹19,999+ / month",
    valueProp: "A receptionist that speaks Hindi, Tamil, and English and never takes a lunch break.",
    problem: "Clinics and solar companies miss 40% of inbound calls.",
    sellerMessage: "Serious buyers only. NDA first. Metrics are live on Stripe India.",
    tech: { frontend: ["Next.js"], backend: ["Python", "Twilio", "Stripe"] },
    channels: ["Outbound", "LinkedIn"],
    listingTier: "scale",
    domainRating: 0,
  },
  {
    slug: "hospo",
    name: "HOSPO",
    tagline: "PMS-lite for 8–40 room hotels",
    description:
      "Check-in, OTA calendar, and GST invoices. Aimed at homestays in Goa, Ooty, and Coorg that can't afford a full Cloudbeds bill.",
    category: "SaaS",
    website: "https://hospo.in",
    logoLetter: "H",
    logoColor: "#D946EF",
    forSale: false,
    revenue30dInr: 1_02_000,
    mrrInr: 97_400,
    allTimeInr: 12_80_000,
    momGrowth: 6,
    activeSubs: 84,
    customers: 84,
    profitMargin: 55,
    provider: "razorpay",
    lastSynced: "2026-08-18T23:12:00+05:30",
    founded: "2023-10-01",
    city: "Goa",
    companyType: "opc",
    founder: { name: "Maria Fernandes", handle: "mariahospo", followers: 3600 },
    vibeCoded: false,
    vibeTools: [],
    funding: "Bootstrapped",
    teamSize: 3,
    audience: "B2B",
    pricing: "₹1,999 / month",
    valueProp: "A homestay can run front desk + GST from a laptop.",
    problem: "Global PMS tools are priced for 200-room hotels and speak zero GST.",
    tech: { frontend: ["Next.js"], backend: ["Rails", "PostgreSQL"] },
    channels: ["Airbnb host groups", "Instagram"],
    listingTier: "free",
    domainRating: 14,
  },
  {
    slug: "agrimandi",
    name: "AgriMandi",
    tagline: "Mandi prices + buyer alerts for FPOs",
    description:
      "Daily APMC prices, WhatsApp alerts, and a simple buyer board. Used by FPOs in Maharashtra and MP.",
    category: "Agri",
    website: "https://agrimandi.in",
    logoLetter: "A",
    logoColor: "#65A30D",
    forSale: false,
    revenue30dInr: 56_200,
    mrrInr: 54_100,
    allTimeInr: 6_40_000,
    momGrowth: 3,
    activeSubs: 41,
    customers: 41,
    profitMargin: 49,
    provider: "payu",
    lastSynced: "2026-08-18T21:00:00+05:30",
    founded: "2023-08-01",
    city: "Nagpur",
    companyType: "pvt-ltd",
    founder: { name: "Suresh Patil", handle: "sureshagri", followers: 1900 },
    vibeCoded: false,
    vibeTools: [],
    funding: "Angel",
    teamSize: 4,
    audience: "B2B",
    pricing: "₹2,499 / month per FPO",
    valueProp: "Farmers sell with yesterday's actual mandi number, not a rumour.",
    problem: "Price discovery still happens on a phone call to a middleman.",
    tech: { frontend: ["Next.js"], backend: ["Python", "PostgreSQL"] },
    channels: ["FPO networks", "Field"],
    listingTier: "free",
    domainRating: 15,
  },
  {
    slug: "lexinote",
    name: "LexiNote",
    tagline: "Case notes for junior litigators",
    description:
      "Voice-to-brief, cause-list reminders, and citation search that knows Indian Kanoon. Vibe-coded by a NALSAR grad.",
    category: "Legal",
    website: "https://lexinote.in",
    logoLetter: "L",
    logoColor: "#78716C",
    forSale: true,
    askingInr: 1_60_000,
    revenue30dInr: 11_800,
    mrrInr: 11_200,
    allTimeInr: 86_000,
    momGrowth: 9,
    activeSubs: 74,
    customers: 80,
    profitMargin: 86,
    provider: "dodo",
    lastSynced: "2026-08-19T08:44:00+05:30",
    founded: "2025-11-01",
    city: "Delhi",
    companyType: "unregistered",
    founder: { name: "Ira Kapoor", handle: "iralaw", followers: 2700, whatsapp: "919811223344" },
    vibeCoded: true,
    vibeTools: ["cursor", "claude"],
    funding: "Bootstrapped",
    teamSize: 1,
    audience: "B2C",
    pricing: "₹399 / month",
    valueProp: "A junior counsel walks into court with a clean brief, not a messy Notes app.",
    problem: "Law interns drown in PDFs and cause lists.",
    sellerMessage: "Joining a chambers full-time. Product is a night-and-weekend app with loyal users.",
    tech: { frontend: ["Next.js"], backend: ["Supabase", "Dodo"] },
    channels: ["Law school groups", "Twitter"],
    listingTier: "starter",
    githubContrib: 92,
    domainRating: 5,
  },
  {
    slug: "hirecampus",
    name: "HireCampus",
    tagline: "Campus drives without 400 Excel sheets",
    description:
      "Colleges publish drives, students apply, companies shortlist. Used by 30+ tier-2 colleges in TN and AP.",
    category: "Education",
    website: "https://hirecampus.in",
    logoLetter: "H",
    logoColor: "#7C3AED",
    forSale: false,
    revenue30dInr: 2_24_000,
    mrrInr: 2_11_000,
    allTimeInr: 18_60_000,
    momGrowth: 8,
    activeSubs: 34,
    customers: 36,
    users: 52000,
    profitMargin: 52,
    provider: "razorpay",
    lastSynced: "2026-08-19T05:33:00+05:30",
    founded: "2024-01-01",
    city: "Hyderabad",
    companyType: "pvt-ltd",
    founder: { name: "Sanjay Reddy", handle: "sanjayhire", followers: 5100 },
    vibeCoded: false,
    vibeTools: [],
    funding: "Bootstrapped",
    teamSize: 5,
    audience: "B2B",
    pricing: "₹14,999 / semester per campus",
    valueProp: "A TPO can run a drive without losing student data in WhatsApp.",
    problem: "Tier-2 placements still run on Google Forms and panic.",
    tech: { frontend: ["Next.js"], backend: ["NestJS", "PostgreSQL"] },
    channels: ["Campus visits", "LinkedIn"],
    listingTier: "free",
    domainRating: 17,
  },
  {
    slug: "tiffinroute",
    name: "TiffinRoute",
    tagline: "Subscription tiffin routes for home cooks",
    description:
      "Home cooks list a weekly menu, collect UPI subscriptions, and get a delivery sequence. 11 cooks in Pune live on it.",
    category: "E-commerce",
    website: "https://tiffinroute.in",
    logoLetter: "T",
    logoColor: "#F59E0B",
    forSale: true,
    askingInr: 3_20_000,
    revenue30dInr: 23_100,
    mrrInr: 22_400,
    allTimeInr: 1_94_000,
    momGrowth: 12,
    activeSubs: 11,
    customers: 11,
    users: 640,
    profitMargin: 38,
    provider: "razorpay",
    lastSynced: "2026-08-19T07:18:00+05:30",
    founded: "2025-06-01",
    city: "Pune",
    companyType: "proprietorship",
    founder: { name: "Pooja Deshpande", handle: "poojatiffin", followers: 860, whatsapp: "919822667788" },
    vibeCoded: true,
    vibeTools: ["lovable", "cursor"],
    funding: "Bootstrapped",
    teamSize: 1,
    audience: "B2B2C",
    pricing: "8% of collection · min ₹999/mo",
    valueProp: "A home cook gets recurring revenue without Swiggy taking 25%.",
    problem: "Tiffin ladies lose customers every time a WhatsApp broadcast is missed.",
    sellerMessage: "Moving cities. 11 cooks, real food, real UPI. Needs a Pune-based operator.",
    tech: { frontend: ["Next.js"], backend: ["Supabase", "Razorpay"] },
    channels: ["Local Instagram", "Housing societies"],
    listingTier: "starter",
    domainRating: 4,
  },
  {
    slug: "studiobook",
    name: "StudioBook",
    tagline: "Bookings for photography studios",
    description:
      "Calendar, packages, GST invoices, and WhatsApp reminders for wedding and portrait studios.",
    category: "SaaS",
    website: "https://studiobook.in",
    logoLetter: "S",
    logoColor: "#FB7185",
    forSale: true,
    askingInr: 2_10_000,
    revenue30dInr: 14_600,
    mrrInr: 14_100,
    allTimeInr: 1_28_000,
    momGrowth: 6,
    activeSubs: 29,
    customers: 29,
    profitMargin: 77,
    provider: "lemonsqueezy",
    lastSynced: "2026-08-18T19:20:00+05:30",
    founded: "2025-09-01",
    city: "Chandigarh",
    companyType: "unregistered",
    founder: { name: "Manav Gill", handle: "manavshoots", followers: 4100, whatsapp: "919888112200" },
    vibeCoded: true,
    vibeTools: ["cursor"],
    funding: "Bootstrapped",
    teamSize: 1,
    audience: "B2B",
    pricing: "₹799 / month",
    valueProp: "Studios stop double-booking Saturday slots.",
    problem: "Wedding season calendars live in a diary behind the reception desk.",
    sellerMessage: "Side project. Happy to sell to a photographer-founder.",
    tech: { frontend: ["Next.js"], backend: ["Supabase"] },
    channels: ["Instagram", "Photographer groups"],
    listingTier: "starter",
    domainRating: 5,
  },
  {
    slug: "fyndly",
    name: "Fyndly",
    tagline: "White-label local services marketplace",
    description:
      "Launch a 'Urban Company for X city' in a week. Bookings, provider payouts, and Razorpay Route.",
    category: "SaaS",
    website: "https://fyndly.in",
    logoLetter: "F",
    logoColor: "#0D9488",
    forSale: false,
    revenue30dInr: 74_500,
    mrrInr: 71_200,
    allTimeInr: 8_10_000,
    momGrowth: 10,
    activeSubs: 18,
    customers: 18,
    profitMargin: 48,
    provider: "razorpay",
    lastSynced: "2026-08-19T04:50:00+05:30",
    founded: "2024-09-01",
    city: "Jaipur",
    companyType: "pvt-ltd",
    founder: { name: "Tanvi Agarwal", handle: "tanvifynd", followers: 2800 },
    vibeCoded: false,
    vibeTools: ["cursor"],
    funding: "Bootstrapped",
    teamSize: 3,
    audience: "B2B",
    pricing: "₹9,999 / month + 2% GMV",
    valueProp: "A city operator gets a marketplace without hiring 6 engineers.",
    problem: "Every city founder wants to clone Urban Company and dies in payments + dispatch.",
    tech: { frontend: ["Next.js", "React Native"], backend: ["NestJS", "PostgreSQL", "Razorpay"] },
    channels: ["LinkedIn", "WhatsApp communities"],
    listingTier: "free",
    domainRating: 13,
  },
];

export function getStartup(slug: string): Startup | undefined {
  return STARTUPS.find((s) => s.slug === slug);
}

export function getFounderStartups(handle: string): Startup[] {
  return STARTUPS.filter((s) => s.founder.handle.toLowerCase() === handle.toLowerCase());
}

export function forSale(): Startup[] {
  return STARTUPS.filter((s) => s.forSale);
}

export function recentlyListed(): Startup[] {
  return [...forSale()].sort((a, b) => (a.founded < b.founded ? 1 : -1));
}

export function bestDeals(): Startup[] {
  return [...forSale()].sort((a, b) => {
    const ma = a.askingInr && a.revenue30dInr ? a.askingInr / (a.revenue30dInr * 12) : 99;
    const mb = b.askingInr && b.revenue30dInr ? b.askingInr / (b.revenue30dInr * 12) : 99;
    return ma - mb;
  });
}

export function leaderboard(): Startup[] {
  return [...STARTUPS].sort((a, b) => b.mrrInr - a.mrrInr);
}

export function categoriesFromData(): { name: string; count: number; mrr: number }[] {
  const map = new Map<string, { count: number; mrr: number }>();
  for (const s of STARTUPS) {
    const cur = map.get(s.category) ?? { count: 0, mrr: 0 };
    cur.count += 1;
    cur.mrr += s.mrrInr;
    map.set(s.category, cur);
  }
  return [...map.entries()]
    .map(([name, v]) => ({ name, ...v }))
    .sort((a, b) => b.mrr - a.mrr);
}
